### ISSUE TITLE
Issue with new repo for php in Yunohost

### ISSUE THREAD

**Issue by Krakinou** [YunoHost-Apps/pilea_ynh#10]
https://forum.yunohost.org/t/nextcloud-15-et-php7-3/7297

It seems that adding https://packages.sury.org/ repo in Yunohost will cause issues in other apps.

**Comment by SimonMellerin** [comment]
Hi, sorry for inconvenience...
I'm gonna work on this but if someone want to help me manage php version, I'll be glad !
For now, I'm gonna with app team how I can quick fix this.

**Comment by supermamie** [comment]
On another topic about this, I found a list of the apps using this repo.
Maybe some of them have solutions :
https://github.com/search?q=org%3AYunoHost-Apps+sury&type=Code

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_add_secure_repos/ynh_add_secure_repos__2

**Comment by SimonMellerin** [comment]
thanks,
I haven't found time yet to fix this, but I hope I'll start this week !

**Comment by SimonMellerin** [comment]
fix with #19
