### ISSUE TITLE
Failed to upgraded pilea_ynh from 0.3.2 to 0.3.8

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/pilea_ynh#14]
from 0.3.2 to 0.3.8

```
Unable to upgrade pilea
/usr/share/yunohost/helpers.d/logging: line 90: args_array: readonly variable
cp: cannot stat '/etc/php/7.2/fpm/pool.d/pilea.conf': No such file or directory
md5sum: /etc/php/7.2/fpm/pool.d/pilea.conf: No such file or directory
/etc/php/7.2/fpm/conf.d/20-pilea.ini wasn't deleted because it doesn't exist.
update-alternatives: warning: forcing reinstallation of alternative /usr/bin/php7.0 because link group php is broken
Now upgrading app pilea…
```

The full logs can be found here : https://paste.yunohost.org/raw/evemukifug

**Comment by SimonMellerin** [comment]
well that's weird
you don't have /etc/php/7.2/fpm/pool.d/pilea.conf file on your server ?
do you have a /etc/php/7.0/fpm/pool.d/pilea.conf instead ?

**Comment by gnouts** [comment]
I can confirm this : https://paste.yunohost.org/raw/enenipivak
Also I tried to delete and reinstall. The install failed too : https://paste.yunohost.org/raw/javukivevu

**Comment by SimonMellerin** [comment]
I'm revamping yunohost Pilea scripts, maybe you can try to install with testing branch, it's almost ready

**Comment by gnouts** [comment]
Indeed, installation worked.
I had issue with some ressources that didn't exist like app.css app.js and some images but some files named "app.fd0bdfe4.js" existed. It broke the site obviously. I managed to make it work by renaming those files.
Still have no data for now, just like https://github.com/YunoHost-Apps/pilea_ynh/issues/13#issuecomment-528758473

**Comment by SimonMellerin** [comment]
> I had issue with some resources that didn't exist like app.css app.js and some images but some files named "app.fd0bdfe4.js" existed. It broke the site obviously. I managed to make it work by renaming those files.

Yep, a little mistake while I generated assets... Testing branch is on pilea 0.3.10 which is broken.. sorry, I push an update to testing branch, should be ok now

**Comment by SimonMellerin** [comment]
@arthurlutz do you still have troubles updating pilea ?

a `touch /etc/php/7.2/fpm/pool.d/pilea.conf` should let you updating pilea but it won't tell us why you don't have this file :/

**Comment by arthurlutz** [comment]
touch of the file doesn't solve the problem. 

I've tried to restore that file from git/etckeeper and touch another ini file which is mentioned but I still end up with a failed upgrade and a deleted file ? 

```
git show fc2bb2e5bbb66fa462a12013e0b7c67b145a4925^:php/7.2/fpm/pool.d/pilea.conf > php/7.2/fpm/pool.d/pilea.conf
touch  /etc/php/7.2/fpm/conf.d/20-pilea.ini
```

**Comment by SimonMellerin** [comment]
Do you still have problem upgrading pilea ?

**Comment by arthurlutz** [comment]
unfortunately yes.

**Comment by SimonMellerin** [comment]
hum so if we can solve this by creating the missing file by hand, an other solution can be :

* backup your Pilea mysql database
* uninstall Pilea
* install Pilea
* import your old database
* play migration to upate pilea if necessary : 
  ``` bash
  cd /var/www/pilea/
  bin/console doctrine:migrations:migrate
  ```

Could be good for you to do this now cause next version of Pilea with bring lot of changes due to news feature (handling users in particular). Operations you will do by hand if you wait too long may be a *bit* more complicated after this update..

**Comment by arthurlutz** [comment]
Got : 

```
bin/console doctrine:migrations:migrate
PHP Fatal error:  Uncaught TypeError: Return value of Symfony\Component\Dotenv\Dotenv::populate() must be an instance of Symfony\Component\Dotenv\void, none returned in /var/www/pilea/vendor/symfony/dotenv/Dotenv.php:145
Stack trace:
#0 /var/www/pilea/vendor/symfony/dotenv/Dotenv.php(468): Symfony\Component\Dotenv\Dotenv->populate(Array, false)
#1 /var/www/pilea/vendor/symfony/dotenv/Dotenv.php(50): Symfony\Component\Dotenv\Dotenv->doLoad(false, Array)
#2 /var/www/pilea/vendor/symfony/dotenv/Dotenv.php(70): Symfony\Component\Dotenv\Dotenv->load('/var/www/pilea/...')
#3 /var/www/pilea/config/bootstrap.php(16): Symfony\Component\Dotenv\Dotenv->loadEnv('/var/www/pilea/...')
#4 /var/www/pilea/bin/console(28): require('/var/www/pilea/...')
#5 {main}
  thrown in /var/www/pilea/vendor/symfony/dotenv/Dotenv.php on line 145

```

**Comment by SimonMellerin** [comment]
my mistake, try 

```
php7.3 bin/console doctrine:migrations:migrate
```

**Comment by arthurlutz** [comment]
@SimonMellerin thanks ! it worked (had to drop/create database because with the restore of the old backup, the table `places` was still there). 

Thanks a bunch!
