### ISSUE TITLE
No data on dashboard after proper credentials settings

### ISSUE THREAD

**Issue by eeaiou** [YunoHost-Apps/pilea_ynh#21]
Hi,
Like the issue #16 , I can't get any data showing up on Pilea.

![Capture d’écran 2020-02-25 à 11 19 48](https://user-images.githubusercontent.com/5105098/75239730-80d67900-57c3-11ea-9875-991abc9c1268.png)

Here is what I see in my logs:
[2020-02-25 11:15:49] php.INFO: Deprecated: Non-static method App\Form\PlaceType::handleSubmit() should not be called statically {"exception":"[object] (ErrorException(code: 0): Deprecated: Non-static method App\\Form\\PlaceType::handleSubmit() should not be called statically at /var/www/pilea/src/Controller/ConfigurationController.php:42)"} []

I don't really know if that's relevant...

Where did I do wrong ?

**Comment by SimonMellerin** [comment]
Data start to appear after ~15min have you waited enough ?

If you visit the config page again, can you see your credentials appear ?

**Comment by SimonMellerin** [comment]
Be aware that Pilea starts to get data only from the day you have configured it, you can't get data from the past (that's coming in a future release)

**Comment by eeaiou** [comment]
> Data start to appear after ~15min have you waited enough ?

No data appears after 15min.

> If you visit the config page again, can you see your credentials appear ?

I don't see the dots in place for the password

![Capture d’écran 2020-02-27 à 12 12 06](https://user-images.githubusercontent.com/5105098/75439611-67b40080-595a-11ea-8cc9-f5affcf8a56d.png)

> Be aware that Pilea starts to get data only from the day you have configured it, you can't get data from the past (that's coming in a future release)

Ok, noted!

**Comment by SimonMellerin** [comment]
> I don't see the dots in place for the password
that's normal

Do you have data in Meteo tab ?

hum, can you log via ssh to you yunohost instance ?
if so, can you try : `ls /etc/cron.d` and see if there's a file named `pilea` in it ?

Then, when you run :
```
cd /var/www/pilea/
php7.3 bin/console pilea:fetch-data true
```
Is there any errors in the console ? Does data appear ?

When you connect to enedis website, can you see your data  ?

**Comment by eeaiou** [comment]
I don't have any data in Meteo tab.

There is a file named Pilea in /etc/cron.d

On the command: php7.3 bin/console pilea:fetch-data true

I get this message:

PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "/var/www/pilea/.env" environment file. in /var/www/pilea/vendor/symfony/dotenv/Doten
v.php:465                                                                                                                                                                            
Stack trace:                                                                                                                                                                         
#0 /var/www/pilea/vendor/symfony/dotenv/Dotenv.php(50): Symfony\Component\Dotenv\Dotenv->doLoad(false, Array)                                                                        
#1 /var/www/pilea/vendor/symfony/dotenv/Dotenv.php(70): Symfony\Component\Dotenv\Dotenv->load('/var/www/pilea/...')                                                                  
#2 /var/www/pilea/config/bootstrap.php(16): Symfony\Component\Dotenv\Dotenv->loadEnv('/var/www/pilea/...')                                                                           
#3 /var/www/pilea/bin/console(28): require('/var/www/pilea/...')                                                                                                                     
#4 {main}                                                                                                                                                                            
  thrown in /var/www/pilea/vendor/symfony/dotenv/Dotenv.php on line 465 

If I sudo the same command, I got no answer.

And there is data on my Enedis account.

**Comment by eeaiou** [comment]
I mistakenly closed this issue...

**Comment by SimonMellerin** [comment]
hum 

When `ls -al /var/www/pilea/`  is there a `.env` file ? what's in it ?
Can you check logs of Pilea installation in '/yunohost/admin/#/tools/logs' to see if you can see an error ?

**Comment by SimonMellerin** [comment]
ah no ok, 

Forget my last comment, that's normal that you can't launch the command when you're not sudo or the pilea linux user

It's also normal that the command returns nothing but that's really strange that nothing happens if there's no error

**Comment by eeaiou** [comment]
> When `ls -al /var/www/pilea/` is there a `.env` file ? what's in it ?

I have a .env file. Here is what's inside:

```
# This file defines all environment variables that the application needs.
# DO NOT DEFINE PRODUCTION SECRETS IN THIS FILE.
# Use ".env.local" for local overrides during development.
# Use real environment variables when deploying to production.
# https://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration

###> symfony/framework-bundle ###
APP_ENV=prod
APP_SECRET=XXXXXXXXXXXXXX
#TRUSTED_PROXIES=127.0.0.1,127.0.0.2
#TRUSTED_HOSTS='^localhost|example\.com$'
###< symfony/framework-bundle ###

###> doctrine/doctrine-bundle ###
# Format described at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
# For an SQLite database, use: "sqlite:///%kernel.project_dir%/var/data.db"
# Configure your db driver and server_version in config/packages/doctrine.yaml
DATABASE_URL=mysql://pilea:**********@127.0.0.1:3306/pilea
###< doctrine/doctrine-bundle ###

###> symfony/swiftmailer-bundle ###
# For Gmail as a transport, use: "gmail://username:password@localhost"
# For a generic SMTP server, use: "smtp://localhost:25?encryption=&auth_mode="
# Delivery is disabled by default via "null://localhost"
MAILER_URL=null://localhost
###< symfony/swiftmailer-bundle ###
```

> Can you check logs of Pilea installation in '/yunohost/admin/#/tools/logs' to see if you can see an error ?

[Here](https://framabin.org/p/?a2c2a5933167e55f#GHHWerWb38yZ2LJcaE4zsJcPhNG0x7CQ6yekQu6t5Uk=) is the full log.

**Comment by eeaiou** [comment]
![Capture d’écran 2020-02-28 à 10 32 12](https://user-images.githubusercontent.com/5105098/75536879-49133f80-5a16-11ea-9f12-70d0a31102b9.png)
![Capture d’écran 2020-02-28 à 10 32 38](https://user-images.githubusercontent.com/5105098/75536896-4e708a00-5a16-11ea-91aa-4ae4d53042c8.png)

That's really strange. I see that I have data showing up on Wednesday only (2,9kWh...)
On the second screenshot, I can only select Feb. 26th. 

On my Enedis account, I see my consumption hourly...

![Capture d’écran 2020-02-28 à 10 40 06](https://user-images.githubusercontent.com/5105098/75537124-bde67980-5a16-11ea-815c-17a1aa3bf725.png)

**Comment by SimonMellerin** [comment]
I think I've found an error in the package.

Try `cat /etc/cron.d/pilea`

It should be written something like `*/10  *  *  *  * #USER# php7.3 #DESTDIR#/bin/console pilea:fetch-data false`
but you have  `*/10  *  *  *  * #USER# php7.2 #DESTDIR#/bin/console pilea:fetch-data false`

That's right ?

**Comment by eeaiou** [comment]
You're right, I got :

`*/10  *  *  *  * pilea php7.2 /var/www/pilea/bin/console pilea:fetch-data false `

**Comment by SimonMellerin** [comment]
shit, so everyone who try to install pilea since last update can't make it work properly...

Try changing php7.2 by php7.3, 

i'm gonna make a fix

**Comment by eeaiou** [comment]
Can you tell me how to change the php version for Pilea ?

I want to be sure that it will not change my set up for Nextcloud...

Don't know if that's connected but [this](https://github.com/YunoHost/issues/issues/1503) doesn't make me so calm!

**Comment by SimonMellerin** [comment]
in fact, PHP7.3 has been installed with Pilea

the only thing you have to do is edit : `*/10 * * * * pilea php7.2 /var/www/pilea/bin/console pilea:fetch-data false` to make it look like `*/10 * * * * pilea php7.3 /var/www/pilea/bin/console pilea:fetch-data false`

**Comment by eeaiou** [comment]
After forcing the php version from 7.2 to 7.3 in the pilea file in /etc/cron.d/, I got this message:

`*/10  *  *  *  * pilea php7.3 /var/www/pilea/bin/console pilea:fetch-data false`

I have now data for yesterday also...

I'll come back in a few days to close this issue.

Thanks a lot!!!

**Comment by SimonMellerin** [comment]
Well, thank you to reporting it !

**Comment by eeaiou** [comment]
Everything's alright here!
This issue can be closed.
