### ISSUE TITLE
Many calls to external domains

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/pilea_ynh#3]
Is it possible to host the external libs needed by this package ?

I am not sure that using CDN is really adapted with self hosting

![screenshot](https://user-images.githubusercontent.com/693751/50736667-92745000-11c0-11e9-8dcc-46628f9a3a7a.png)

**Comment by SimonMellerin** [comment]
Yep, I agree with that !

I'm porting Pilea to Symfony 4, and doing this, i'm also rewritting the front using 'modern' JS tools.
It should be available soon !

**Comment by maniackcrudelis** [comment]
Is closing this issue means that your work on this matter is already done ?

**Comment by SimonMellerin** [comment]
no the work is in progress.
I've closed this issue because the question has been answered

But, thinking about it, I suppose this issue should be closed when the work will be released

**Comment by supermamie** [comment]
It seems this has been fixed in Pilea v0.3.0 one month ago, is it possible to update the YunoHost app to get the latest version ?

**Comment by SimonMellerin** [comment]
yep, i'm working on it.
I'm gonna post on the yunohost forum, I need some people to test the upgrade.

It's already in the testing branch if you want

**Comment by supermamie** [comment]
I just tried 
`sudo yunohost app upgrade pilea -u https://github.com/YunoHost-Apps/pilea_ynh/tree/testing --debug`

But I still have the same problem I had on the forum saying there is nothing to save, which block the install

```14446 WARNING 3415 Impossible de sauvegarder l’application « pilea »
14448 WARNING Traceback (most recent call last):
14448 WARNING   File "/usr/lib/moulinette/yunohost/backup.py", line 685, in _collect_app_files
14449 WARNING     raise_on_error=True, chdir=tmp_app_bkp_dir, env=env_dict)
14449 WARNING   File "/usr/lib/moulinette/yunohost/hook.py", line 390, in hook_exec
14450 WARNING     raise YunohostError('hook_exec_failed', path=path)
14450 WARNING YunohostError: Échec de l’exécution du script « /tmp/backup_z8ehZ2 »
14451 WARNING 3418 Il n’y a rien à sauvegarder
14577 ERROR Impossible de mettre à jour pilea
14592 INFO L’opération « Mettre à jour l’application « pilea » » a échouée ! Pour avoir de l’aide, merci de partager le log de cette opération en utilisant la commande « yunohost log display 20190222-084653-app_upgrade-pilea --share »
14598 DEBUG action [25323.1] executed in 13.989s
14599 DEBUG lock has been released
14600 ERROR Aucune application à mettre à jour

**Comment by SimonMellerin** [comment]
Arf...

May be you can try to:

- backup your database with PhpMyAdmin (all pilea data are in it, there's nothing more to backup)
- uninstall Pilea
- reinstall Pilea with master branch
- import your backup
- You should see all your data appear in Pilea
- Try to update with test branch to test the upgrade

**Comment by supermamie** [comment]
That is exactly what I did for last Pilea upgrade, but I tried again and now... I'm in 0.3.2 :smile:

**Comment by SimonMellerin** [comment]
good !
If you try to backup your pilea from yunohost backoffice, does it work ?
I'm gonna post on yunohost forum, if you have some suggestions/problem with this v0.3.2 post over there :)

**Comment by supermamie** [comment]
The save is OK but much bigger than the save before the upgrade (63Mo before, 114Mo after)
No problem found yet, all seems great :+1:

**Comment by SimonMellerin** [comment]
well I suppose it's because there's no more call to external domains and everything is now packed in the app :wink:

**Comment by supermamie** [comment]
Which is... exactly the point of this issue, awesome :smile:

**Comment by SimonMellerin** [comment]
resolved with https://github.com/YunoHost-Apps/pilea_ynh/pull/9
