### ISSUE TITLE
Composer sous Yunohost plante et annule l'installation.

### ISSUE THREAD

**Issue by Yohmm** [YunoHost-Apps/pilea_ynh#34]
Bonjour,

J'attendais depuis quelques temps une nouvelle version de Pilea, ou d'Aeneria compatible avec le nouveau système d'Enedis, et je suis très content de voir que le développement se passe bien !
Malheureusement, lorsque j'ai voulu installer Pilea sur mon serveur Yunohost, une erreur avec Composer est apparu. Voici le log d'installation : 

https://paste.yunohost.org/raw/fuqepahabe

> 020-11-07 01:34:50,279: DEBUG - + echo '[########++++........] > Installing Composer...'
> 2020-11-07 01:34:50,279: DEBUG - + ynh_install_composer --phpversion=7.3 --workdir=/var/www/pilea
> 2020-11-07 01:34:50,280: DEBUG - + declare -Ar args_array
> 2020-11-07 01:34:50,280: DEBUG - + workdir=/var/www/pilea
> 2020-11-07 01:34:50,280: DEBUG - + COMPOSER_HOME=/var/www/pilea/.composer
> 2020-11-07 01:34:50,280: DEBUG - + php7.3 -- --quiet --install-dir=/var/www/pilea
> 2020-11-07 01:34:50,280: DEBUG - + curl -sS https://getcomposer.org/installer
> 2020-11-07 01:34:50,882: DEBUG - + ynh_composer_exec --phpversion=7.3 --workdir=/var/www/pilea '--commands=install --no-dev'
> 2020-11-07 01:34:50,882: DEBUG - + declare -Ar args_array
> 2020-11-07 01:34:50,883: DEBUG - + workdir=/var/www/pilea
> 2020-11-07 01:34:50,883: DEBUG - + COMPOSER_HOME=/var/www/pilea/.composer
> 2020-11-07 01:34:50,883: DEBUG - + php7.3 /var/www/pilea/composer.phar install --no-dev -d /var/www/pilea --quiet --no-interaction
> 2020-11-07 01:34:51,084: DEBUG - + ynh_die '--message=Unable to update core dependencies with Composer.'
> 2020-11-07 01:34:51,084: WARNING - Your lock file does not contain a compatible set of packages. Please run composer update.
> 2020-11-07 01:34:51,186: DEBUG - + ret_code=1
> 2020-11-07 01:34:51,186: WARNING - Unable to update core dependencies with Composer.
> 2020-11-07 01:34:51,187: DEBUG - + echo 'Unable to update core dependencies with Composer.'
> 2020-11-07 01:34:51,187: DEBUG - + exit 1
> 2020-11-07 01:34:51,187: DEBUG - + ynh_exit_properly
> 2020-11-07 01:34:51,187: DEBUG - + local exit_code=1
> 2020-11-07 01:34:51,188: DEBUG - + '[' 1 -eq 0 ']'
> 2020-11-07 01:34:51,188: DEBUG - + trap '' EXIT
> 2020-11-07 01:34:51,188: DEBUG - + set +o errexit
> 2020-11-07 01:34:51,188: DEBUG - + set +o nounset
> 2020-11-07 01:34:51,188: DEBUG - + sleep 0.5
> 2020-11-07 01:34:51,594: DEBUG - + type -t ynh_clean_setup
> 2020-11-07 01:34:51,595: DEBUG - + exit 1
> 2020-11-07 01:34:51,627: ERROR - Could not install pilea: An error occurred inside the app installation script

Serveur physique : VMWare Esxi, Intel(R) Xeon(R) CPU E3-1240 V2, 16 Go RAM
Serveur virtuel :  YunoHost 4.0.8.2, 1 vcpu, 2Go RAM

Il s'agissait d'une installation reprise de zéro depuis l'interface webadmin.

Merci encore pour cette application !

**Comment by Nartagnan** [comment]
Bonjour,
J'ai exactement le même problème.
Voici le log de mon coté :
https://paste.yunohost.org/raw/xupixiweso

Merci et bonne journée

**Comment by SimonMellerin** [comment]
Bonjour,

Désolé, je n'ai pas beaucoup le temps de travailler sur aeneria en ce moment, je vais essayer de réparer ça rapidement.

Par contre, si vous n'avez pas déjà pilea d'installé, cela ne sert à rien de l'installer maintenant, cette version n'est plus fonctionnelle (cf #29 & #25) 

Je vais modifier le readme pour que ça soit plus clair.

Bonne journée

**Comment by SimonMellerin** [comment]
Le bug est réparé sur la dernière version du package.

Il provenait du fait que le script d'install du package utilise par défaut la dernière version de composer qui est maintenant la version 2. Une petite mise à jour du fichier de dépendances était donc nécessaire.

Mais cette nouvelle version n'est à utiliser que pour mettre à jour une instance existante pour pouvoir exporter ces données.

Je le lance maintenant dans le packaging d'aeneria !

Simon
