### ISSUE TITLE
When configuring the " Compteur Linky " part we get a 500 error

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/pilea_ynh#6]
Entering city names in "Nom du compteur" we get 

```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

Using the "Numéro de mon point de livraison" (PDL) seems to not generate an error.

**Comment by SimonMellerin** [comment]
Hi,

What city name did you try ?

**Comment by arthurlutz** [comment]
Sèvres

**Comment by SimonMellerin** [comment]
That's weird :/ it works when I test it :(

Is there other fields that behave like this ?
'Nom du compteur', 'adresse' and 'Nom MeteoFrance' are been developed the same way.

Could you access logs in `/var/www/pilea/var/log/` folder ?

Anyway, these fields will disappear in the next release of Pilea cause I don't really use them. I will only keep the 'address' field which could be used for future features.

**Comment by SimonMellerin** [comment]
should be resolved with https://github.com/YunoHost-Apps/pilea_ynh/pull/9
